# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/test/.opencode/freearc/srep

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/test/.opencode/freearc/srep

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/home/test/.local/lib/python3.8/site-packages/cmake/data/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/test/.opencode/freearc/srep/CMakeFiles /home/test/.opencode/freearc/srep//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/test/.opencode/freearc/srep/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named srep

# Build rule for target.
srep: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 srep
.PHONY : srep

# fast build rule for target.
srep/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/srep.dir/build.make CMakeFiles/srep.dir/build
.PHONY : srep/fast

Compression/Common.o: Compression/Common.cpp.o
.PHONY : Compression/Common.o

# target to build an object file
Compression/Common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/srep.dir/build.make CMakeFiles/srep.dir/Compression/Common.cpp.o
.PHONY : Compression/Common.cpp.o

Compression/Common.i: Compression/Common.cpp.i
.PHONY : Compression/Common.i

# target to preprocess a source file
Compression/Common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/srep.dir/build.make CMakeFiles/srep.dir/Compression/Common.cpp.i
.PHONY : Compression/Common.cpp.i

Compression/Common.s: Compression/Common.cpp.s
.PHONY : Compression/Common.s

# target to generate assembly for a file
Compression/Common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/srep.dir/build.make CMakeFiles/srep.dir/Compression/Common.cpp.s
.PHONY : Compression/Common.cpp.s

Compression/SREP/srep.o: Compression/SREP/srep.cpp.o
.PHONY : Compression/SREP/srep.o

# target to build an object file
Compression/SREP/srep.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/srep.dir/build.make CMakeFiles/srep.dir/Compression/SREP/srep.cpp.o
.PHONY : Compression/SREP/srep.cpp.o

Compression/SREP/srep.i: Compression/SREP/srep.cpp.i
.PHONY : Compression/SREP/srep.i

# target to preprocess a source file
Compression/SREP/srep.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/srep.dir/build.make CMakeFiles/srep.dir/Compression/SREP/srep.cpp.i
.PHONY : Compression/SREP/srep.cpp.i

Compression/SREP/srep.s: Compression/SREP/srep.cpp.s
.PHONY : Compression/SREP/srep.s

# target to generate assembly for a file
Compression/SREP/srep.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/srep.dir/build.make CMakeFiles/srep.dir/Compression/SREP/srep.cpp.s
.PHONY : Compression/SREP/srep.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... srep"
	@echo "... Compression/Common.o"
	@echo "... Compression/Common.i"
	@echo "... Compression/Common.s"
	@echo "... Compression/SREP/srep.o"
	@echo "... Compression/SREP/srep.i"
	@echo "... Compression/SREP/srep.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

