name: CI Cmake

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ubuntu-latest, windows-latest]  # 支持的操作系统列表

    steps:
    - uses: actions/checkout@v4

    - name: Build srep
      run: |
        mkdir build
        cd build
        cmake ..
        ls
        make
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: executable-${{ matrix.os }}
        path: ./  # 替换为你可执行文件的路径
